spring:
  datasource:
    url: 'jdbc:h2:mem:planetdb:SCHEMA=sw'
    driverClassName: 'org.h2.Driver'
    username: 'sa'
    password: ''
  h2:
    console:
      enabled: 'true'
  liquibase:
    change-log: 'classpath:liquibase-changeLog.xml'
    url: 'jdbc:h2:mem:planetdb:SCHEMA=sw'
    user: 'sa'
    password: ''
  jpa:
    hibernate:
      ddl-auto: 'none'
    database-platform: 'org.hibernate.dialect.H2Dialect'